export enum EventType {
  METER_CREATED = 'meter_created',
  METER_UPDATED = 'meter_updated',
  AREA_CREATED = 'area_created',
  AREA_UPDATED = 'area_updated',
  METER_TARIFF_CREATED = 'meter_tariff_created',
  METER_TARIFF_UPDATED = 'meter_tariff_updated',
  AREA_TARIFF_CREATED = 'area_tariff_created',
  AREA_TARIFF_UPDATED = 'area_tariff_updated',
  METER_ASSIGNED = 'meter_assined',
  METER_UNASSIGNED = 'meter_unassinged',
  SINGLE_METER_BILL_GENERATED = 'single_meter_bill_ generated',
  AREA_CONSOLIDATED_BILL_GENERATED = 'area_consolidated_bill_generated',
  CUSTOMER_CONSOLIDATED_BILL_GENERATED = 'customer_consolidated_bill_generated',
}
